### ISSUE TITLE
Keyboard shortcut to "RUN" a SQL statement.

### ISSUE THREAD

**Issue by sfd99** [MCodrescu/octopus#2]
**Marcus:**

PKG is very useful.
_Good idea._

**Q:**
Can you please add 
a **_Keyboard shortcut_** 
to "RUN" any SQL statement.

**Reason:**
after I type any SQL statement
(on the right Pane),
I still have to 
manually scroll 
all the way down the page,
to find and click on the Form [ RUN ] button!.

The key: **[ F5 ]** 
would be nice = RUN any SQL statement
already on the right Pane!.

+ It would also be helpful
if you added 
a **_Keyboard shortcut_** 
to " VIEW " the DB,
(the form [ VIEW ] button is also waaaay down!...).

_Thanks!_
**sfd99
San Francisco
Rstudio / Ubuntu Linux / Octopus 0.1.2 f/ CRAN**

**Comment by MCodrescu** [comment]
Thanks for the idea! I will definitely look into keyboard shortcuts. Can you share a screenshot of your app interface? What does 'way down' look like on your setup? Do you have the browser maximized?

**Comment by MCodrescu** [comment]
I added support for hotkeys. You can expect this to be added in the next CRAN release but in the meantime, you can use `devtools::install_github("MCodrescu/octopus")` to install the updated version. 

You can now click Ctrl-Shift-Enter (CMD-SHIFT-ENTER) to run a query and Ctrl-Shift-F (CMD-SHIFT-F) to format a query. Make sure your cursor is inside of the text editor when you do so.

**Comment by sfd99** [comment]
**Hi Marcus,**

2 Shortcut Keys
you just added
work really well.

An easy suggestion 
( I think...):

After the user
has [ RUN ] the SQL script
and seen the results,
pressing [ ESC ] key
will show the main Octopus Form again.
Fine! :-)

But,
at that point,
can you _(please!)_
**place the mouse cursor
(automatically) back
in the SQL Editor Pane,** 
ready for the user to (maybe) change the SQL script
and [ RUN ] again.

i.e. :
just restore the mouse cursor
exactly where it was before the user pressed  [ RUN ].

That makes
the User "flow"
much easier and faster,
( instead of the user having
to _manually_ click 
to place the mouse cursor again 
in the SQL area ,
after a [ RUN ]... ).

Just suggesting
to make Octopus better and better
(and even easier to use...).  :-)

**_Thanks!_
sfd99
San Francisco
Rstudio / Ubuntu Linux / Octopus 0.1.2 DL f/ DEVTOOLS (latest).**

**Comment by MCodrescu** [comment]
I like that suggestion. Would you create a new issue and paste the above into it?

**Comment by MCodrescu** [comment]
The modal popup that shows the data will disappear if you hit the Escape key and your cursor will still be wherever it was before. However, if you hit the format key, then it does reset your cursor to the front.

**Comment by sfd99** [comment]
Hmmm....
the "format" key?
I'm on LINUX  (not MAC)
Which keyboard key is that, Marcus?

**Comment by MCodrescu** [comment]
I am referring to either the Format button in the interface or Ctrl-Shift-F (CMD-SHIFT-F).

**Comment by sfd99** [comment]
oh - I see.
Let me try that...

**Comment by sfd99** [comment]
ok - the SQL editor area has:
select * from mtcars limit 6

**1)**  I press:  CTRL-SHIFT-ENTER

**2)**  I see the results (6 rows) ok!

**3)**  Instead of [ESC],
     I press:  CTRL-SHIFT-F
     while seeing the 6 result rows.
     But nothing happens after I press: CTRL-SHIFT-F

**4)**  I then have to press [ESC] 
     to see
     the Octopus Main form with the SQL script,
     but the cursor 
    is not restored / not visible at all 
     in the SQL Editor.

**Comment by MCodrescu** [comment]
On step 3 you pressed CTRL-SHIFT-F, but that only formats the query itself, it doesn't close the modal. Use ESC to close the modal popup. You should click CTRL-SHIFT-F to format the query before you run it.

Formatting the query will take SELECT * FROM mtcars LIMIT 6 and format it to

SELECT *
FROM mtcars
LIMIT 6

Although formatting a query may not work if you are using a VPN.

**Comment by sfd99** [comment]
Ah, understood
the sequence.
Trying that next...just a sec.
(btw: I'm not using a VPN...)

**Comment by sfd99** [comment]
ok-
1) Ctrl-Shift-F to reformat the code (before I run it),
 to:
SELECT *
FROM mtcars
LIMIT 6

2) [RUN] it (Ctrl-Shift-Enter) 

3) I see the 6 rows result.

4) I press [DISMISS] or [ESC]

5) I see the main form
  with the formatted SQL.
But the cursor is not restored. No cursor visible.

Marcus - I'm missing some step?
